### ISSUE TITLE
Add profile back but put the note in it

### ISSUE THREAD

**Issue by exvuma** [exvuma/wedding#48]
- [x] She must be at the very end 
- [x] Put that a little explainer like 
- [x] Use her original photo 

> Guliette is no longer in the wedding party not because she was kicked out, but because of turmoil that existed for years. We love Guliette and are happy she has decided to save her funds for a trip to Europe. 

 https://docs.google.com/document/d/1ZCqBw2UMt14imVuYKxJRHPDjcf5-sGZYAfriMddMYdE/edit#bookmark=id.9zd236kys4bx 

Nice to have:

- [ ] Style it so she is like muted

**Comment by vapurrmaid** [comment]
@exvuma - this is kind of amazing. Sorry for sniping a random issue/comment, wanted to say hi 👋🏻 and send some posi vibes ⭐

**Comment by exvuma** [comment]
@vapurrmaid  you made my day <3 you have no need how much I needed that. Want me to assign to you?? haha jkjk unless you want to I miss working with you let's catch up soon  🥰. (After i turn back sane ,I've been a 👰‍♀️🧟‍♀️)

**Comment by davidBubela** [comment]
@exvuma Added her profile back as is at the end w/out the explanation as I consider that beyond the scope of myself.

**Comment by vapurrmaid** [comment]
> @vapurrmaid you made my day <3 you have no need how much I needed that. Want me to assign to you?? haha jkjk unless you want to I miss working with you let's catch up soon 🥰. (After i turn back sane ,I've been a 👰‍♀️🧟‍♀️)

Let's catchup on the Discords sometime! :D
